2024-03-13 17:50:29,896 [ERROR] django.request: Internal Server Error: /ru/shop/products/latest/feed/
Traceback (most recent call last):
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/sentry_sdk/integrations/django/views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 40, in __call__
    feedgen = self.get_feed(obj, request)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 194, in get_feed
    self._get_dynamic_attr("item_link", item),
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/contrib/syndication/views.py", line 103, in _get_dynamic_attr
    return attr(obj)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/python_django/mysite/shopapp/views.py", line 94, in item_link
    return reverse("shopapp:product_detail", kwargs={"pk": item.pk})
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/aa_lozovoy/PycharmProjects/pythonProject/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product_detail' not found. 'product_detail' is not a valid view function or pattern name.
